"""Terminal UI rendering — backward compatibility wrapper."""

from __future__ import annotations

from agents.tui import (
    console,
    _safe_text,
    _safe_stdout_write,
    COOKIE_BEAR,
    print_welcome,
    print_user_prompt,
    print_user_message,
    print_input_metadata,
    print_assistant_text,
    print_assistant_footer,
    print_error,
    print_confirmation,
    print_divider,
    print_cost,
    print_retry,
    print_info,
    print_warning,
    print_goodbye,
    print_interrupted,
    print_processing_status,
    print_plan_for_approval,
    print_plan_approval_options,
    print_sub_agent_start,
    print_sub_agent_end,
    SPINNER_FRAMES,
    start_spinner,
    stop_spinner,
    print_thinking_text,
    reset_thinking_window,
    set_thinking_visible,
    thinking_visible,
    print_tool_call,
    print_tool_result,
    print_context_rows,
    print_memory_entries,
    print_session_rows,
    print_trace_rows,
    print_skill_entries,
    md_render_enabled,
    md_looks_renderable,
    md_track_begin,
    md_track_feed,
    md_track_flush,
    theme,
)
from agents.tui.tables import _shorten_path, _relative_time, _trace_summary
from agents.tui.markdown import _md_count_rows
from agents.tui import thinking as _thinking_module


def __getattr__(name: str):
    if name in ("_thinking_buffer", "_thinking_drawn_rows", "_thinking_started", "_THINKING_WINDOW_LINES"):
        return getattr(_thinking_module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "console",
    "_safe_text",
    "_safe_stdout_write",
    "COOKIE_BEAR",
    "print_welcome",
    "print_user_prompt",
    "print_user_message",
    "print_input_metadata",
    "print_assistant_text",
    "print_assistant_footer",
    "print_error",
    "print_confirmation",
    "print_divider",
    "print_cost",
    "print_retry",
    "print_info",
    "print_warning",
    "print_goodbye",
    "print_interrupted",
    "print_processing_status",
    "print_plan_for_approval",
    "print_plan_approval_options",
    "print_sub_agent_start",
    "print_sub_agent_end",
    "SPINNER_FRAMES",
    "start_spinner",
    "stop_spinner",
    "print_thinking_text",
    "reset_thinking_window",
    "set_thinking_visible",
    "thinking_visible",
    "print_tool_call",
    "print_tool_result",
    "print_context_rows",
    "print_memory_entries",
    "print_session_rows",
    "print_trace_rows",
    "print_skill_entries",
    "md_render_enabled",
    "md_looks_renderable",
    "md_track_begin",
    "md_track_feed",
    "md_track_flush",
    "theme",
    "_shorten_path",
    "_relative_time",
    "_trace_summary",
    "_md_count_rows",
    "_thinking_buffer",
    "_thinking_drawn_rows",
    "_thinking_started",
    "_THINKING_WINDOW_LINES",
]
